---
- name: Add apt-repo fluxgui
  apt_repository:
    repo: ppa:nathan-renniewaldock/flux
    state: present

- name: Install fluxgui
  apt:
    name: fluxgui
    state: latest
    update_cache: yes
