---
- name: Setup Mac OS X
  import_tasks: mac-setup.yaml
  when: ansible_distribution == 'MacOSX'

- name: Setup Linux
  import_tasks: linux-setup.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
