---
- name: Add apt-key spotify
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
    state: present

- name: Add apt-repo spotify
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Install spotify
  apt:
    name: spotify-client
    state: latest
    update_cache: yes
